version: '3.2'

services:
  redis:
    image: redis:latest
    volumes:
      - redis-data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  server:
    build:
      context: ./
    command: node server.js
    env_file:
      - .env
    volumes:
      - sqlite:/sqlite
      - pdfs:/pdfs
    restart: unless-stopped
    ports:
      - '8000:8000'
    depends_on:
      - redis

volumes:
  redis-data:
  sqlite:
  pdfs:
